### ISSUE TITLE
QUESTION: Need help to deploy Rally micro-service

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/service-rally#10]
Hi,

I recently built reportportal & trying to integrate it with Rally. I gone-through the installation page, but couldn't find steps to deploy Rally micro-service. I don't have prior experience in deploying micro-service in docker container. 

Can you please help me with steps to deploy rally micro service in reportportal app?

I'm using RHEL7, centos-7 docker engine & compose. I deployed the reportportal app with the standard docker-compose.yml provided in the installation guide.

Thanks,
Arun

**Comment by mcafeerun** [comment]
Hi @avarabyeu, Thanks for your reply!

When i navigate to project settings > Bug tracking System, i see a message "To configure Bug Tracking System, please deploy appropriate micro-service". The drop down is disabled.. 

![image](https://user-images.githubusercontent.com/36393899/37310946-ff08be54-261b-11e8-8ca9-e18b28c6d1ee.png)

**Comment by avarabyeu** [comment]
what is output of `docker ps`?

**Comment by mcafeerun** [comment]
Here you go.. 

CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                                        NAMES
1fb5ebbae3b6        reportportal/service-api:3.3.2             "/start.sh"              23 hours ago        Up 23 hours         8080/tcp                                                     reportportal_api_1
69704c6b0243        reportportal/service-authorization:3.3.0   "/start.sh"              23 hours ago        Up 23 hours         8080/tcp                                                     reportportal_uat_1
ac76d41e3f80        reportportal/service-index:3.1.1           "/service-index"         23 hours ago        Up 23 hours         8080/tcp                                                     reportportal_index_1
821b843274e3        consul:0.9.3                               "docker-entrypoint..."   23 hours ago        Up 23 hours         8300-8302/tcp, 8500/tcp, 8301-8302/udp, 8600/tcp, 8600/udp   reportportal_registry_1
4e125ca98635        mongo:3.4                                  "docker-entrypoint..."   23 hours ago        Up 23 hours         27017/tcp                                                    reportportal_mongodb_1
ae51258b0a0b        fabiolb/fabio:1.5.2-go1.9                  "/fabio -cfg /etc/..."   23 hours ago        Up 23 hours         0.0.0.0:9998->9998/tcp, 0.0.0.0:8080->9999/tcp               reportportal_gateway_1
3abce421eb84        reportportal/service-ui:3.3.2              "/service-ui"            23 hours ago        Up 23 hours         8080/tcp                                                     reportportal_ui_1

**Comment by mcafeerun** [comment]
I think my docker-compose.yml does not have rally API service. I will try to deploy the service and update comments.. Sorry for oversight..

**Comment by mcafeerun** [comment]
Hi @avarabyeu ,

I have redeployed the app with rally service.. Still is see the same message when i navigate to project settings > Bug tracking System, i see a message "**To configure Bug Tracking System, please deploy appropriate micro-service**". The drop down is disabled..

Here is the output of my  docker-compose ps


  ```
       Name                        Command               State                                              Ports
---------------------------------------------------------------------------------------------------------------------------------------------------------------
reportportal_api_1        /start.sh                        Up      8080/tcp
reportportal_gateway_1    /fabio -cfg /etc/fabio/fab ...   Up      0.0.0.0:9998->9998/tcp, 0.0.0.0:8080->9999/tcp
reportportal_index_1      /service-index                   Up      8080/tcp
reportportal_mongodb_1    docker-entrypoint.sh mongod      Up      27017/tcp
reportportal_rally_1      /start.sh                        Up      8080/tcp
reportportal_registry_1   docker-entrypoint.sh agent ...   Up      8300/tcp, 8301/tcp, 8301/udp, 8302/tcp, 8302/udp, 0.0.0.0:8500->8500/tcp, 8600/tcp, 8600/udp
reportportal_uat_1        /start.sh                        Up      8080/tcp
reportportal_ui_1         /service-ui                      Up      8080/tcp

```

**Comment by mcafeerun** [comment]
Hi, Can someone help me with this issue?

**Comment by avarabyeu** [comment]
@mcafeerun that's strange since now rally service is UP. The only thing i can suggest is to stop everything, remove data/consul service and start again. Sometimes consul cache doesn't getting updated properly.

**Comment by avarabyeu** [comment]
btw, make sure you use all latest 3x versions (or 4x if you use fourth  version of RP)

**Comment by mcafeerun** [comment]
@avarabyeu  -  I did full cleanup and redeployed the app from the scratch.. I took the latest version of report portal image (image: reportportal/service-rally:4.0.0)..

```
            Name                          Command               State                                              Ports
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
reportportal_analyzer_1        /service-analyzer                Up      8080/tcp
reportportal_api_1             /start.sh                        Up      8080/tcp
reportportal_elasticsearch_1   /usr/local/bin/docker-entr ...   Up      9200/tcp, 9300/tcp
reportportal_gateway_1         /fabio -cfg /etc/fabio/fab ...   Up      0.0.0.0:9998->9998/tcp, 0.0.0.0:8080->9999/tcp
reportportal_index_1           /service-index                   Up      8080/tcp
reportportal_mongodb_1         docker-entrypoint.sh mongod      Up      27017/tcp
reportportal_rally_1           /start.sh                        Up      8080/tcp
reportportal_registry_1        docker-entrypoint.sh agent ...   Up      8300/tcp, 8301/tcp, 8301/udp, 8302/tcp, 8302/udp, 0.0.0.0:8500->8500/tcp, 8600/tcp, 8600/udp
reportportal_uat_1             /start.sh                        Up      8080/tcp
reportportal_ui_1              /service-ui                      Up      8080/tcp
```

Still i see the drop down is disabled..

**Comment by evjlobanova** [comment]
@mcafeerun is issue reproducing now?

**Comment by mcafeerun** [comment]
@avarabyeu @evjlobanova  - I'm sorry. I thought i closed this issue. Its working fine.
