### ISSUE TITLE
Rally integration: Add possibility to configure some Rally projects on one RP project

### ISSUE THREAD

**Issue by e-olga** [reportportal/service-rally#2]
It would be great to have an ability to add some Rally bts instances on one Report Portal project from backend and ui sides

**Comment by DzmitryHumianiuk** [comment]
Is it working on API level?
Only UI side required?

**Comment by e-olga** [comment]
@DzmitryHumianiuk: Yes, it works on API level.
So, we need improvement on UI side only

**Comment by e-olga** [comment]
@DzmitryHumianiuk: Yes, it's possible to create some connections via API
So, improvement on UI side need only

**Comment by DzmitryHumianiuk** [comment]
available with 4.0 version

**Comment by e-olga** [comment]
Fully implemented with RP v. 5.0
