### ISSUE TITLE
Environment field is not persisted on Project Settings page

### ISSUE THREAD

**Issue by madhead** [reportportal/service-rally#6]
I'm trying to persist default values for submitting bugs in Rally. I've set an `Environment` field to one of available values (`Development`):

![image](https://cloud.githubusercontent.com/assets/577360/25668431/5239f176-302f-11e7-99e9-2beaef3d10f1.png)

After submitting this form the value is back to `Select value`:

![image](https://cloud.githubusercontent.com/assets/577360/25668481/6fccc434-302f-11e7-8a6b-f00540c137f0.png)

I think there is a bug handling this particular field that may be related to #4.

**Comment by ayarmakovich** [comment]
It might be connected with the types of drop-down select fields.
We have 2 types of drop-downs in Bug form.

The first type is a simple drop-down without search. It's Schedule State field for instance.
If we look at the HTML code of such drop-down, we will see the selected value INSIDE the tag of the drop-down:
![image](https://cloud.githubusercontent.com/assets/12941032/25941391/f98c3e6c-3641-11e7-9afd-f05ae9752ebc.png)

The second type is a drop-down with search for particular option in it (not simple).
It's Environment field for instance.
If we look at the HTML code of such drop-down, we will see the selected value OUTSIDE the tag of the drop-down:
![image](https://cloud.githubusercontent.com/assets/12941032/25941502/746398e2-3642-11e7-8128-05e759ed92ed.png)

So it might be the actual reason why the second type drop-downs fields are submitted with null values.
And at the same time the first type drop-downs fields are submitted with the correct selected values.

**Comment by avarabyeu** [comment]
@e-olga Can we try to reproduce?

**Comment by DzmitryHumianiuk** [comment]
issue related to multi-workspaces functionality of Rally.
integration should be extended to support it

**Comment by e-olga** [comment]
@avarabyeu  For testing we have simple drop down w/o 'Select value' field for 'Environment' list 
![environment field_rally](https://cloud.githubusercontent.com/assets/22497746/25943516/c640143c-3648-11e7-9a35-d243aab69a5b.png)
So, I am not able to reproduce the situation above.

**Comment by glukin** [comment]
The root cause has been identified and fixed (see reportportal/service-ui#252).
